import Link from "next/link";
import { ArrowLeft, Shield } from "lucide-react";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background pb-16">
      <div className="max-w-lg mx-auto px-4 pt-6 space-y-5">
        <div className="flex items-center gap-3">
          <Link
            href="/profile"
            className="flex h-8 w-8 items-center justify-center rounded-full hover:bg-muted transition-colors"
          >
            <ArrowLeft size={18} />
          </Link>
          <div className="flex items-center gap-2">
            <Shield size={18} className="text-primary" />
            <div>
              <h1 className="text-lg font-bold">Privacy Policy</h1>
              <p className="text-xs text-muted-foreground">Last updated May 2026</p>
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-border bg-card px-6 py-5 space-y-5 text-sm leading-relaxed">
          <Section title="1. Information We Collect">
            We collect information you provide directly (name, email, phone number, emergency contact) and information generated by your use of the service (trip routes, GPS location during active trips, payment method type, and notification preferences).
          </Section>

          <Section title="2. How We Use Your Information">
            We use your information to: provide and improve our services, process payments, send trip and payment notifications, display live trip tracking, and comply with legal obligations. We do not sell your personal data to third parties.
          </Section>

          <Section title="3. Location Data">
            GPS location is collected only during active trips and is used to track your route and calculate trip distance. Location data is stored for 90 days and then automatically deleted. You can disable location sharing in your device settings, but this will prevent live tracking features from working.
          </Section>

          <Section title="4. Payment Information">
            Card payments are processed by Stripe. TaxiFlow does not store full card numbers. We store only the payment method type and the last 4 digits of the card for display purposes. Stripe&apos;s privacy policy applies to payment data.
          </Section>

          <Section title="5. Data Sharing">
            We share data only as necessary to provide the service (e.g., with payment processors) or when required by law. We do not share your personal information with advertisers.
          </Section>

          <Section title="6. Data Retention">
            We retain your account data for as long as your account is active. Trip history is retained for 3 years. You may request deletion of your account and associated data at any time from the Profile page.
          </Section>

          <Section title="7. Security">
            We use industry-standard encryption (TLS/SSL) for data in transit and encrypt sensitive fields at rest. Access to production databases is restricted to authorised personnel.
          </Section>

          <Section title="8. Your Rights">
            You have the right to access, correct, and delete your personal data. You may download a copy of your data from Profile → Download My Data. To request account deletion, use Profile → Delete Account.
          </Section>

          <Section title="9. Cookies">
            We use cookies solely for session management (keeping you logged in). We do not use tracking or advertising cookies.
          </Section>

          <Section title="10. Contact">
            For privacy-related questions or data requests, contact our Data Protection Officer at{" "}
            <span className="text-primary">privacy@taxiflow.et</span>.
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="font-semibold text-foreground mb-1">{title}</p>
      <p className="text-muted-foreground">{children}</p>
    </div>
  );
}
